---
all:
  children:
    app_servers:
      hosts:
        app_server:
          ansible_host: 65.2.142.108
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sduse/.ssh/devops.pem
          app_port: 3000
          node_version: "20.x"
    
    db_servers:
      hosts:
        db_server:
          ansible_host: 3.110.124.162
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sduse/.ssh/devops.pem
          mongodb_version: "7.0"
          mongodb_port: 27017
    
    monitoring_servers:
      hosts:
        nagios_server:
          ansible_host: 13.201.19.105
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sduse/.ssh/devops.pem
          nagios_admin_user: nagiosadmin
          nagios_admin_password: "changeme123"
